### ISSUE TITLE
Block - Zwave_preamble_0 cannot be evaluated.

### ISSUE THREAD

**Issue by sizemorebrian** [AFITWiSec/EZ-Wave#17]
When running ./install.sh grc I'm getting the following error.

```
Validation failed:
Block - Zwave_preamble_0 - Preamble(Zwave_preamble):
	Param - preamble length(preamble_length):
		Value "" cannot be evaluated:
		Cannot evaluate empty statement.
Error during file compilation.
```

I compared my local copy of /usr/local/share/gnuradio/grc/blocks/Zwave_preamble.xml to the current version and it is identical.

**Comment by sizemorebrian** [comment]
Not sure where to start debugging an issue like this, if you could just point me in the right direction I'll see if I can find a solution.

**Comment by cwbadenhop** [comment]
I may have broken something on my last commit. I suspect there is a python
issue where the Preamble block is defined with the length parameter but
somewhere the constructor is called without the parameter.

**Comment by sizemorebrian** [comment]
Gonna go ahead and close the issue for you. Your explanation implies that I didn't config the install correctly. No longer working with the software, but seems like not an issue with EZ-Wave.
