### ISSUE TITLE
gnuradio installation

### ISSUE THREAD

**Issue by laithmatalkah** [AFITWiSec/EZ-Wave#2]
I'am a beginner in this field .  where should you recommend install gnuradio
in /home/user/  or in the root directory?? please provide me an example by using pybombs. I am so confused, because  everything was going well until I run ./install.sh blocks in scapy radio. 

something called grcc and gnuradio run-time are missing

**Comment by gitjhall** [comment]
Duplicate of https://github.com/AFITWiSec/EZ-Wave/issues/1
