### ISSUE TITLE
For Pentoo Linux: ImportError: No module named Zwave

### ISSUE THREAD

**Issue by ktreyburn** [AFITWiSec/EZ-Wave#8]
When I try to run the Zwave.grc I keep getting this error. I have tried the install twice with no success. I have not been able find anything on this issue. 
<<< Welcome to GNU Radio Companion 3.7.8 >>>

Preferences file: /root/.grc
Block paths:
	/usr/local/share/gnuradio/grc/blocks
	/usr/share/gnuradio/grc/blocks
	/root/.grc_gnuradio

Showing: ""

Loading: "/root/EZ-Wave-master/setup/Zwave.grc"
>>> Done

Showing: "/root/EZ-Wave-master/setup/Zwave.grc"

Generating: "/root/EZ-Wave-master/setup/top_block.py"

Executing: "/root/EZ-Wave-master/setup/top_block.py"

_Traceback (most recent call last):
  **File "/root/EZ-Wave-master/setup/top_block.py", line 30, in <module>
    import Zwave
ImportError: No module named Zwave**_

**Comment by ktreyburn** [comment]
This also happened for Zigbee.grc and the BT4LE.grc

**Comment by cwbadenhop** [comment]
Have you added /usr/local/share/gnuradio/grc/blocks to global_blocks_path in /etc/gnuradio/conf.d/grc.conf?

**Comment by ktreyburn** [comment]
# This file contains system wide configuration data for GNU Radio.
# You may override any setting on a per-user basis by editing
# ~/.gnuradio/config.conf

[grc]
global_blocks_path = /usr/share/gnuradio/grc/blocks:/usr/local/share/gnuradio/grc/blocks
local_blocks_path =
xterm_executable = x-terminal-emulator
canvas_font_size = 8
canvas_default_size = 1280, 1024

**Comment by ktreyburn** [comment]
I have solved the issue being starting from scratch and installing using the sudo command on everything in Ubuntu. Also the original error occurred on a pentoo install.
