### ISSUE TITLE
Problem to compile wireshark :packet-afit-encapse.c:117:145: error: enum conversion when passing argument 4 of 'register_dissector_table'

### ISSUE THREAD

**Issue by cloatre** [AFITWiSec/EZ-Wave#9]
Hello,

With last version of wireshark, the prototype of function "register_dissector_table" has changed so the code does not compile:

  CC       packet-afit-encapse.lo
packet-afit-encapse.c: In function 'proto_register_afit_encap':
packet-afit-encapse.c:117:145: error: enum conversion when passing argument 4 of 'register_dissector_table' is invalid in C++ [-Werror=c++-compat]
    afit_encap_dissector_table = register_dissector_table("afit_encap.encap_type", "Temporary Encapsulation Type for ZWAVE dissector", FT_UINT8, BASE_DEC);

-->
diff --git a/epan/packet.h b/epan/packet.h
index f1f0862..1d44b92 100644 (file)
--- a/epan/packet.h
+++ b/epan/packet.h
@@ -186,14 +186,14 @@ WS_DLL_PUBLIC void dissector_all_tables_foreach_table (DATFunc_table func,
  * case-sensitive)
  */
 WS_DLL_PUBLIC dissector_table_t register_dissector_table(const char *name,
-    const char *ui_name, const ftenum_t type, const int param, dissector_table_allow_e allow_dup);
+    const char *ui_name, const int proto, const ftenum_t type, const int param, dissector_table_allow_e allow_dup);

**Comment by cwbadenhop** [comment]
What version of Wireshark are you using?

**Comment by cloatre** [comment]
I think it was the 2.0.4 or 2.1.0.
I change to the 1.2.0 and I get no problem of compilation.
